language: python
sudo: required
dist: xenial

addons:
  postgresql: "9.5"

services:
  - docker
  - mysql

before_script:
  - psql -c 'create database sqlalchemy_utils_test;' -U postgres
  - psql -c 'create extension hstore;' -U postgres -d sqlalchemy_utils_test
  - mysql -e 'create database sqlalchemy_utils_test;'

matrix:
  include:
  - python: 3.6
    env:
      - "TOXENV=py36"
  - python: 3.7
    env:
      - "TOXENV=py37"
  - python: 3.8
    env:
      - "TOXENV=py38"
  - python: 3.9
    env:
      - "TOXENV=py39"

install:
  - source $TRAVIS_BUILD_DIR/.travis/install_mssql.sh
  - pip install tox

script:
  - tox
