addons:
  postgresql: 9.3

before_script:
  - psql -c 'create database sqlalchemy_utils_test;' -U postgres


language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

env:
  matrix:
    - SQLALCHEMY=SQLAlchemy==0.9
    - SQLALCHEMY=SQLAlchemy==0.8.4

install:
  - "pip install $SQLALCHEMY"
  - pip install -e ".[test]"
script:
  - python setup.py test
