addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database sqlalchemy_utils_test;' -U postgres
  - psql -c 'create extension hstore;' -U postgres -d sqlalchemy_utils_test
  - mysql -e 'create database sqlalchemy_utils_test;'

language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - EXTRAS=test
  - EXTRAS=test_all

install:
  - pip install -e .[$EXTRAS]

script:
  - isort --recursive --diff sqlalchemy_utils tests && isort --recursive --check-only sqlalchemy_utils tests
  - flake8 sqlalchemy_utils tests
  - py.test
